In [7]:
import pandas as pd
df = pd.read_csv("results.csv")
df["model"] = df["model"].apply(lambda s: s[:-1])
df["date"] = pd.to_datetime(df["time"]).dt.day

In [8]:
df = df[df["date"]==7]

In [12]:
min_df = df.groupby(["model", "seed"]).min()
min_df.groupby("model").mean()

                epoch  train  val  date
model
3dsincos-1000N   0.00   0.52 1.03  7.00
3dsincos-100N    0.00   0.50 1.04  7.00
3dsincos-10N     0.00   0.51 1.07  7.00
default-1000N    0.00   0.27 0.64  7.00
default-100N     0.00   0.25 0.64  7.00
default-10N      0.00   0.27 0.66  7.00
noemb-1000N      0.00   0.20 0.65  7.00
noemb-100N       0.00   0.22 0.67  7.00
noemb-10N        0.00   0.24 0.68  7.00
sincos-1000N     0.00   0.24 0.64  7.00
sincos-100N      0.00   0.25 0.63  7.00
sincos-10N       0.00   0.27 0.65  7.00

In [13]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
min_df.groupby("model").std()

                epoch  train  val  date
model
3dsincos-1000N   0.00   0.04 0.02  0.00
3dsincos-100N    0.00   0.04 0.03  0.00
3dsincos-10N     0.00   0.07 0.07  0.00
default-1000N    0.00   0.02 0.03  0.00
default-100N     0.00   0.03 0.01  0.00
default-10N      0.00   0.02 0.01  0.00
noemb-1000N      0.00   0.01 0.01  0.00
noemb-100N       0.00   0.02 0.02  0.00
noemb-10N        0.00   0.01 0.01  0.00
sincos-1000N     0.00   0.02 0.01  0.00
sincos-100N      0.00   0.04 0.01  0.00
sincos-10N       0.00   0.03 0.02  0.00